### PR TITLE
Move scripts into `src` directory [breaking]

### PR DESCRIPTION
**Pull request by Nick-Mazuk**
This PR moves all the scripts into a `/src` directory. This should lead to better organization in the future, and will make it easier to create downloadable versions of each script. Discussed in https://github.com/Nick-Mazuk/jw-lua-scripts/issues/70

**Breaking change**: Anyone who currently uses this repo to run these scripts will have to "reregister" them with JW Lua.

### CODE REVIEW

**Review by rpatters1 — COMMENTED** [review]
Does `.gitignore` need to be changed as well (now that `script_settings` will be in `src`)?

(I'm not sure it does, but it's worth checking.)

**Comment by Nick-Mazuk** [comment]
@rpatters1  Just checked, and no, the `.gitignore` does not need to be changed.

**Review by rpatters1 — APPROVED** [review]
Looks good.

**Review by rpatters1 — APPROVED** [review]
looks good

**Pull request merged**
