### PR TITLE
Connect docs with docs site

### LINKED ISSUE #55: Generate docs automatically
**Is your feature request related to a problem? Please describe.**

As the repo is growing, especially as the library is growing, I figured it might be time to get some documentation going. This could aid both documenting what certain functions do as well as helping get started with contributing/using the scripts. This issue is mainly concerned over documenting the library code, though.

**Describe the solution you'd like**

In other languages, there are tools to generate documentation automatically from the code (e.g., JSDoc for JavaScript), so I started looking if there was anything for Lua. Turns out, there is.

I propose we add the [Lua docs generator Github Action](https://github.com/marketplace/actions/lua-docs-generator) to the repo. This action will run on every commit/push to the Master branch and generate documentation based on our comments.

```lua
-- library/general_library.lua

--[[ General:library.add_augmentation_dot(entry)
Accepts a FC:NoteEntry() object and adds an augmentation dot. Useful for…
--]]

function library.add_augmentation_dot(entry)
    entry.Duration = bit32.bor(entry.Duration, bit32.rshift(entry.Duration, 1))
end
```

This will generate several MarkDown files, which we can either put in the repo's Wiki (see the "Wiki" tab at the top of the repo), or I can setup a quick site and make it easy to search through all the docs. Either way is fine with me, and if I setup a site, I already have most of the boilerplate done from other projects.

@rpatters1 , @CJGarciaMusic , have any thoughts? If this sounds like something worth doing, I'll go ahead and start exploring the action more to provide more details.

### PR DESCRIPTION
**Pull request by Nick-Mazuk**
This PR does 2 things:

1. Adds 4 new pages of docs (e.g., getting started)
2. Connects docs to website

**Note**: This PR may contain bugs. More on this later.

## New docs

For the most part, the 4 new pages of docs come from the Readme and the Style Guide. Just making sure everything is in one central place. I also added some docs on how to document functions in the library.

## Website

To make the docs easier to search through and read, I created a website for them. I'm hoping we could potentially use the site in the future as well (e.g., for letting people find scripts and download them easily, even if they don't know how to use GitHub). But for now, it can serve as a home for the docs.

https://jw-lua-scripts-docs.vercel.app/docs/getting-started

This PR extends the GitHub action I setup over the weekend to generate the Library docs by also copying over the docs to the repo that contains the website. Then, that other repo will automatically deploy the site. This means, to update the website, we just need to update this repo.

**However**, I do not know for sure if this GitHub action is error free. There's no good way to run this action locally. If this PR is approved and merged, I'll go ahead and debug everything (which may result in several failed runs and lots of commits tomorrow).

Close #55

### CODE REVIEW

**Review by rpatters1 — APPROVED** [review]
This looks really good. I think it might be a good idea to add a link to the website from the readme.md file. Right now the readme mentions the library, so perhaps that is a good jumping off point.

Also, the website you mentioned in the PR appears to be the JetStream website. I am not sure if that's because this PR needs to be merged first or what. But I thought I'd mention it.

Finally, I've been holding off doing documenting any of the stuff I added because I figured it would be better to wait to the approach is finalized. But I noticed you have taken on at least some of that in this PR. If you are ready for me to pitch in, say the word.

**Comment by rpatters1** [comment]
P.S. Merge at your convenience.

**Comment by rpatters1** [comment]
Another issue I meant to raise is, the snake-case naming convention seems to be interfering with the markup language. That is:

`this_variable_name` is being rendered in the markup as this_variable_name.

**Comment by Nick-Mazuk** [comment]
> This looks really good. I think it might be a good idea to add a link to the website from the readme.md file. Right now the readme mentions the library, so perhaps that is a good jumping off point.

I agree. We could potentially even shorten the readme to the duplicate info.

> the website you mentioned in the PR appears to be the JetStream website

It shouldn't be the JetStream website… Don't know why it's appearing to be that site for you.


> Finally, I've been holding off doing documenting any of the stuff I added because I figured it would be better to wait to the approach is finalized. But I noticed you have taken on at least some of that in this PR. If you are ready for me to pitch in, say the word.

Pitch in whenever you're ready! Anything in the `/docs` folder will be added to the website. If you want to add a new page, just add a new Markdown file.

> Another issue I meant to raise is, the snake-case naming convention seems to be interfering with the markup language. That is:
> 
> `this_variable_name` is being rendered in the markup as this _variable_ name.
> 
> It could just be a bug in the md editor I'm using, though. Not sure.

With the snake case, I believe that is not a bug with your markdown editor. We'll have to watch out to ensure that all variable names use the back ticks to make them code blocks.

**Pull request merged**
