### PR TITLE
Update readme + move style guide

### PR DESCRIPTION
**Pull request by Nick-Mazuk**
Because of the new docs site, this PR simplifies the Readme.

- Readers are pointed to the docs for more details
- The "Resources" section in the current Readme is moved to the docs
- Also added quick explanation on how to use the scripts
- Move style guide to docs (instead of a markdown file in the repo)

### CODE REVIEW

**Comment by Nick-Mazuk** [comment]
FYI, feel free to update the docs whenever you want.

**Comment by rpatters1** [comment]
If I update the library .lua script files with decorations, will the merge
automatically rebuild the docs? Or do I need to take further steps?

Thanks,
Robert

**Comment by Nick-Mazuk** [comment]
@rpatters1 The docs will rebuild. No need to do anything else.

**Review by rpatters1 — APPROVED** [review]
I thought I approved this awhile back. Looks good.

**Pull request merged**
